name: Remote Release

on:
  release:
    types: [published]

jobs:
  fetch-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      
      - name: Checkout edatasheets.github.io
        uses: actions/checkout@v4
        with:
          repository: willcalar91/release.test.edatasheet.github.io
          path: edatasheets.github.io
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Run release script
        run: bash release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate branch name
        id: generate_branch
        run: echo "branch=release-${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Get release author
        id: get_author
        run: |
          echo "author_name=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }} | jq -r '.author.login')" >> $GITHUB_ENV
          echo "author_email=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/${{ env.author_name }} | jq -r '.email')" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          cd edatasheets.github.io
          git checkout -b ${{ env.branch }}
          git config --global user.name "${{ env.author_name }}"
          git config --global user.email "${{ env.author_email }}"
          git add .
          git commit -m "Release ${{ github.event.release.tag_name }}"
          git push origin HEAD

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: willcalar91/release.test.edatasheet.github.io
          event-type: create-release-pull-request
          client-payload: |-
            {
              "release":{
                "tag_name":"${{ github.event.release.tag_name }}",
                "body":"${{ github.event.release.body }}"
              }
            }
            
