name: Release

on:
  workflow_dispatch:

  release:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      
      - name: Checkout edatasheets.github.io
        uses: actions/checkout@v4
        with:
          repository: willcalar91/release.test.edatasheet.github.io
          path: edatasheets.github.io
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Run release script
        run: bash release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Create pull request
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: standard-release
          delete-branch: true
          title: '[Example] Release'
          body: |
            This is an automated pull request to update the report for the new release.
          labels: |
            release
            automated pr
          milestone: 1
          draft: false
