name: Release electronic datasheets standard

on:
  release:
    types: [published]

jobs:
  fetch-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: willcalar91/release.test.edatasheet.github.io
          event-type: create-release-pull-request
          client-payload: |-
            {
              "release":{
                "tag_name":"${{ github.event.release.tag_name }}",
                "body":"${{ github.event.release.body }}"
              }
            }
            
