name: Release

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Checkout edatasheets.github.io
        uses: actions/checkout@v4
        with:
          repository: edatasheets/edatasheets.github.io
          path: edatasheets.github.io

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      #- name: Run release script
      #  run: bash release.sh
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
