name: Release

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Checkout edatasheets.github.io
        uses: actions/checkout@v4
        with:
          repository: willcalar91/release.test.edatasheet.github.io
          path: edatasheets.github.io

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Run release script
        run: bash release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          cd edatasheets.github.io
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          BRANCH_NAME="update-release-artifacts-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update release artifacts"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/willcalar91/release.test.edatasheet.github.io.git $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Update release artifacts"
          branch: $BRANCH_NAME
          title: "Update release artifacts"
          body: "This PR updates the release artifacts."
          base: main
          path: edatasheets.github.io
