name: Remote Release

on:
  release:
    types: [published]

jobs:
  fetch-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      
      - name: Checkout edatasheets.github.io
        uses: actions/checkout@v4
        with:
          repository: willcalar91/release.test.edatasheet.github.io
          path: edatasheets.github.io
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Run release script
        run: bash release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate branch name
        id: generate_branch
        run: echo "branch=release-${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Checkout to new branch
        run: |
          cd edatasheets.github.io
          git checkout -b ${{ env.branch }}

      - name: Commit changes
        run: |
          cd edatasheets.github.io
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release ${{ github.event.release.tag_name }}"
          git push origin ${{ env.branch }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: willcalar91/release.test.edatasheet.github.io
          event-type: create-release-pull-request
          client-payload: |-
            {
              "release":{
                "tag_name":"${{ github.event.release.tag_name }}",
                "body":"${{ github.event.release.body }}"
              }
            }
            
